spring:
  application:
    name: search-university-for-china
  main:
    web-application-type: none
    banner-mode: off # 关闭 banner 避免stdio传输不相关数据
  ai:
    mcp:
      server:
        stdio: true # 开始 standard input/output 模式
        name: search-university-for-china # 服务名称 使用时显示的server名称
        version: 0.0.1
logging:
  level:
    root: off # 关闭 日志 避免stdio传输不相关数据
free-api:
  # 大学信息
  url1: https://api.52vmy.cn/api/query/daxue
  # girl image
  url2: https://jx.ykapi.top/API/hqyyid.php
  # girl video
  url3: https://api.52vmy.cn/api/img/tu/girl
  # 今日头条
  url4: http://is.snssdk.com/api/news/feed/v51/
  # Bing 壁纸
  url5: https://api.asilu.com/bg/
  # 实时段子
  url6: https://api.apiopen.top/getJoke
